spring.redis:
  host: redis
  port: 6379
#  password:
  database: 0
  timeout: 5000
  lettuce:
    pool:
      # 连接池最大连接数（使用负值表示没有限制） 默认 8
      max-active: 100
      # 连接池中的最大空闲连接 默认 8
      max-idle: 100
      # 连接池中的最小空闲连接 默认 0
      min-idle: 0
      # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
      max-wait: -1ms
      time-between-eviction-runs: 30000
    shutdown-timeout: 200ms
# redis en
