spring.datasource:
  username: tutorial
  password: tutorial-123e
  url: jdbc:mysql://localhost:3306/tutorial_springboot_test
  driver-class-name: com.mysql.cj.jdbc.Driver

spring.redis:
  host: 127.0.0.1
  port: 6379
  password: redis
  database: 3
  timeout: 3000
  lettuce:
    pool:
      # 连接池最大连接数（使用负值表示没有限制） 默认 8
      max-active: 100
      # 连接池中的最大空闲连接 默认 8
      max-idle: 100
      # 连接池中的最小空闲连接 默认 0
      min-idle: 0
      # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
      max-wait: -1ms
      time-between-eviction-runs: 30000
    shutdown-timeout: 200ms
# redis end


test.name-name: DDD
bees360.com.system-config:
  web-server: http://localhost:8080/bees360-web

server:
  port: 9090